### ISSUE TITLE
Need to get coverage for 3.x to 3.x migrations

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/mig-ci#95]
Assume source is 3.x and destination is 3.x

Would like to see a:
  3.7 -> 3.7
  3.7 -> 3.11

**Comment by fbladilo** [comment]
@jwmatthews Partially covered with #118 , except for same release migrations.

**Comment by fbladilo** [comment]
Closing this one , this capability has been on mig-ci for quite some time.
