### ISSUE TITLE
Need to get coverage for 4.x to 4.x migrations

### ISSUE THREAD

**Issue by jwmatthews** [konveyor/mig-ci#96]
Assume source is 4.2 and destination is 4.2

Looking to ensure we catch issues of 4 -> 4 migrations.

@sseago ran into some issues today in this scenario, we need to get some more tests fleshing out issues.

**Comment by fbladilo** [comment]
@jwmatthews Also partially covered by #118 , same release migrations are not. I will send a separate PR for that alone.

**Comment by fbladilo** [comment]
Closing this one, capability has been in place for quite some time.
